### ISSUE TITLE
Where did the QP kernel come from?

### ISSUE THREAD

**Issue by timothydmorton** [RuthAngus/GProtation#13]
Did you guys invent/construct it specifically for this purpose?  Or has it been used in other purposes and you identified it as useful and adapted it?

**Comment by RuthAngus** [comment]
Suzanne first suggested it and I think she got it from the Mauna Loa CO2 problem in Rasmussen and Williams http://www.gaussianprocess.org/gpml/chapters/RW5.pdf (see pages 119 and 120)

**Comment by timothydmorton** [comment]
OK-- I'll leave it up to you if you think that should be referenced or not.

**Comment by RuthAngus** [comment]
Yeah, I'll add it!
