### ISSUE TITLE
Move section 3.3

### ISSUE THREAD

**Issue by dfm** [RuthAngus/GProtation#15]
I think that section 3.3 describing the GP method should be its own section because it really is the heart of this paper. Then the other methods should be described in subsections _after_ the GP section. What do y'all think?

**Comment by timothydmorton** [comment]
Yeah, I'm up for reorganization suggestions; something does feel a bit funny about the current organization.

**Comment by timothydmorton** [comment]
Maybe 
\section{Literature Methods}

\section{GP Method}
?

**Comment by dfm** [comment]
I would go for something more like

\section{Our awesome method}

\section{Performance & comparison to literature}

I think that the GP section should be first because it doesn't really rely on the others and it is the whole point!

**Comment by timothydmorton** [comment]
Ah, yes, I like this.  Describe the method before we actually apply it and do the comparison.  In this case, should we describe the simulation data later too?  Or do you think that is fine to be in Section 2 (with a bit of rewording that I can work on)?

**Comment by timothydmorton** [comment]
I will reorganize as I edit sections 2-end.  Good suggestion!
